/** All currencies belonging to the group `Currency` (Currency) */
export enum Currency {
  alt = "alt",
  fusing = "fusing",
  alch = "alch",
  chaos = "chaos",
  gcp = "gcp",
  exalted = "exalted",
  chrome = "chrome",
  jewellers = "jewellers",
  engineers = "engineers",
  "infused-engineers-orb" = "infused-engineers-orb",
  chance = "chance",
  chisel = "chisel",
  scour = "scour",
  blessed = "blessed",
  regret = "regret",
  regal = "regal",
  divine = "divine",
  vaal = "vaal",
  annul = "annul",
  "orb-of-binding" = "orb-of-binding",
  "ancient-orb" = "ancient-orb",
  "orb-of-horizons" = "orb-of-horizons",
  "harbingers-orb" = "harbingers-orb",
  wisdom = "wisdom",
  portal = "portal",
  scrap = "scrap",
  whetstone = "whetstone",
  bauble = "bauble",
  transmute = "transmute",
  aug = "aug",
  mirror = "mirror",
  eternal = "eternal",
  "rogues-marker" = "rogues-marker",
  facetors = "facetors",
  "prime-regrading-lens" = "prime-regrading-lens",
  "secondary-regrading-lens" = "secondary-regrading-lens",
  "tempering-orb" = "tempering-orb",
  "tailoring-orb" = "tailoring-orb",
  "awakened-sextant" = "awakened-sextant",
  "elevated-sextant" = "elevated-sextant",
  "surveyors-compass" = "surveyors-compass",
  "orb-of-unmaking" = "orb-of-unmaking",
  "blessing-xoph" = "blessing-xoph",
  "blessing-tul" = "blessing-tul",
  "blessing-esh" = "blessing-esh",
  "blessing-uul-netol" = "blessing-uul-netol",
  "blessing-chayula" = "blessing-chayula",
  "veiled-chaos-orb" = "veiled-chaos-orb",
  "enkindling-orb" = "enkindling-orb",
  "instilling-orb" = "instilling-orb",
  "sacred-orb" = "sacred-orb",
  "stacked-deck" = "stacked-deck",
}

/** All currencies belonging to the group `ExoticCurrency` (Exotic Currency) */
export enum ExoticCurrency {
  "crusaders-exalted-orb" = "crusaders-exalted-orb",
  "redeemers-exalted-orb" = "redeemers-exalted-orb",
  "hunters-exalted-orb" = "hunters-exalted-orb",
  "warlords-exalted-orb" = "warlords-exalted-orb",
  "awakeners-orb" = "awakeners-orb",
  "mavens-orb" = "mavens-orb",
  "eldritch-chaos-orb" = "eldritch-chaos-orb",
  "eldritch-exalted-orb" = "eldritch-exalted-orb",
  "eldritch-orb-of-annulment" = "eldritch-orb-of-annulment",
  "lesser-eldritch-ember" = "lesser-eldritch-ember",
  "greater-eldritch-ember" = "greater-eldritch-ember",
  "grand-eldritch-ember" = "grand-eldritch-ember",
  "exceptional-eldritch-ember" = "exceptional-eldritch-ember",
  "lesser-eldritch-ichor" = "lesser-eldritch-ichor",
  "greater-eldritch-ichor" = "greater-eldritch-ichor",
  "grand-eldritch-ichor" = "grand-eldritch-ichor",
  "exceptional-eldritch-ichor" = "exceptional-eldritch-ichor",
  "orb-of-conflict" = "orb-of-conflict",
  "tainted-chromatic-orb" = "tainted-chromatic-orb",
  "tainted-orb-of-fusing" = "tainted-orb-of-fusing",
  "tainted-jewellers-orb" = "tainted-jewellers-orb",
  "tainted-chaos-orb" = "tainted-chaos-orb",
  "tainted-exalted-orb" = "tainted-exalted-orb",
  "tainted-mythic-orb" = "tainted-mythic-orb",
  "tainted-armourers-scrap" = "tainted-armourers-scrap",
  "tainted-blacksmiths-whetstone" = "tainted-blacksmiths-whetstone",
  "tainted-divine-teardrop" = "tainted-divine-teardrop",
  "tainted-blessing" = "tainted-blessing",
  "wild-lifeforce" = "wild-lifeforce",
  "vivid-lifeforce" = "vivid-lifeforce",
  "primal-lifeforce" = "primal-lifeforce",
  "sacred-lifeforce" = "sacred-lifeforce",
  "armour-recombinator" = "armour-recombinator",
  "weapon-recombinator" = "weapon-recombinator",
  "jewellery-recombinator" = "jewellery-recombinator",
}

/** All currencies belonging to the group `Splinters` (Shards & Splinters) */
export enum Splinters {
  "annulment-shard" = "annulment-shard",
  "mirror-shard" = "mirror-shard",
  "exalted-shard" = "exalted-shard",
  "binding-shard" = "binding-shard",
  "horizon-shard" = "horizon-shard",
  "harbingers-shard" = "harbingers-shard",
  "engineers-shard" = "engineers-shard",
  "ancient-shard" = "ancient-shard",
  "chaos-shard" = "chaos-shard",
  "regal-shard" = "regal-shard",
  "splinter-xoph" = "splinter-xoph",
  "splinter-tul" = "splinter-tul",
  "splinter-esh" = "splinter-esh",
  "splinter-uul" = "splinter-uul",
  "splinter-chayula" = "splinter-chayula",
  "timeless-eternal-empire-splinter" = "timeless-eternal-empire-splinter",
  "timeless-karui-splinter" = "timeless-karui-splinter",
  "timeless-vaal-splinter" = "timeless-vaal-splinter",
  "timeless-templar-splinter" = "timeless-templar-splinter",
  "timeless-maraketh-splinter" = "timeless-maraketh-splinter",
  "simulacrum-splinter" = "simulacrum-splinter",
  "crescent-splinter" = "crescent-splinter",
  "ritual-splinter" = "ritual-splinter",
}

/** All currencies belonging to the group `Fragments` (Fragments & Sets) */
export enum Fragments {
  dusk = "dusk",
  mid = "mid",
  dawn = "dawn",
  noon = "noon",
  grie = "grie",
  rage = "rage",
  hope = "hope",
  ign = "ign",
  hydra = "hydra",
  phoenix = "phoenix",
  minot = "minot",
  chimer = "chimer",
  "fragment-of-enslavement" = "fragment-of-enslavement",
  "fragment-of-eradication" = "fragment-of-eradication",
  "fragment-of-constriction" = "fragment-of-constriction",
  "fragment-of-purification" = "fragment-of-purification",
  "fragment-of-terror" = "fragment-of-terror",
  "fragment-of-emptiness" = "fragment-of-emptiness",
  "fragment-of-shape" = "fragment-of-shape",
  "fragment-of-knowledge" = "fragment-of-knowledge",
  "al-hezmins-crest" = "al-hezmins-crest",
  "barans-crest" = "barans-crest",
  "droxs-crest" = "droxs-crest",
  "veritanias-crest" = "veritanias-crest",
  "victorious-fate" = "victorious-fate",
  "deadly-fate" = "deadly-fate",
  "will-of-chaos" = "will-of-chaos",
  "ignominious-fate" = "ignominious-fate",
  offer = "offer",
  "offer-tribute" = "offer-tribute",
  "offer-gift" = "offer-gift",
  "offer-dedication" = "offer-dedication",
  "sacrifice-set" = "sacrifice-set",
  "mortal-set" = "mortal-set",
  "shaper-set" = "shaper-set",
  "key-to-decay" = "key-to-decay",
  "maddening-object" = "maddening-object",
  "crest-of-the-elderslayers" = "crest-of-the-elderslayers",
  "xophs-breachstone" = "xophs-breachstone",
  "tuls-breachstone" = "tuls-breachstone",
  "eshs-breachstone" = "eshs-breachstone",
  "uul-breachstone" = "uul-breachstone",
  "chayulas-breachstone" = "chayulas-breachstone",
  "xophs-charged-breachstone" = "xophs-charged-breachstone",
  "tuls-charged-breachstone" = "tuls-charged-breachstone",
  "eshs-charged-breachstone" = "eshs-charged-breachstone",
  "uul-charged-breachstone" = "uul-charged-breachstone",
  "chayulas-charged-breachstone" = "chayulas-charged-breachstone",
  "xophs-enriched-breachstone" = "xophs-enriched-breachstone",
  "tuls-enriched-breachstone" = "tuls-enriched-breachstone",
  "eshs-enriched-breachstone" = "eshs-enriched-breachstone",
  "uul-enriched-breachstone" = "uul-enriched-breachstone",
  "chayulas-enriched-breachstone" = "chayulas-enriched-breachstone",
  "xophs-pure-breachstone" = "xophs-pure-breachstone",
  "tuls-pure-breachstone" = "tuls-pure-breachstone",
  "eshs-pure-breachstone" = "eshs-pure-breachstone",
  "uul-pure-breachstone" = "uul-pure-breachstone",
  "chayulas-pure-breachstone" = "chayulas-pure-breachstone",
  "xophs-flawless-breachstone" = "xophs-flawless-breachstone",
  "tuls-flawless-breachstone" = "tuls-flawless-breachstone",
  "eshs-flawless-breachstone" = "eshs-flawless-breachstone",
  "uul-flawless-breachstone" = "uul-flawless-breachstone",
  "chayulas-flawless-breachstone" = "chayulas-flawless-breachstone",
  "timeless-eternal-emblem" = "timeless-eternal-emblem",
  "timeless-karui-emblem" = "timeless-karui-emblem",
  "timeless-vaal-emblem" = "timeless-vaal-emblem",
  "timeless-templar-emblem" = "timeless-templar-emblem",
  "timeless-maraketh-emblem" = "timeless-maraketh-emblem",
  "uber-timeless-eternal-emblem" = "uber-timeless-eternal-emblem",
  "uber-timeless-karui-emblem" = "uber-timeless-karui-emblem",
  "uber-timeless-vaal-emblem" = "uber-timeless-vaal-emblem",
  "uber-timeless-templar-emblem" = "uber-timeless-templar-emblem",
  "uber-timeless-maraketh-emblem" = "uber-timeless-maraketh-emblem",
  simulacrum = "simulacrum",
  "sacred-blossom" = "sacred-blossom",
  "ritual-vessel" = "ritual-vessel",
  "the-atlas" = "the-atlas",
  "the-formed" = "the-formed",
  "the-twisted" = "the-twisted",
  "the-forgotten" = "the-forgotten",
  "the-hidden" = "the-hidden",
  "the-feared" = "the-feared",
  "the-elderslayers" = "the-elderslayers",
  "the-mavens-writ" = "the-mavens-writ",
  "writhing-invitation" = "writhing-invitation",
  "screaming-invitation" = "screaming-invitation",
  "polaric-invitation" = "polaric-invitation",
  "incandescent-invitation" = "incandescent-invitation",
  "ancient-reliquary-key" = "ancient-reliquary-key",
  "timeworn-reliquary-key" = "timeworn-reliquary-key",
  "vaal-reliquary-key" = "vaal-reliquary-key",
  "forgotten-reliquary-key" = "forgotten-reliquary-key",
  "visceral-reliquary-key" = "visceral-reliquary-key",
  "shiny-reliquary-key" = "shiny-reliquary-key",
  "archive-reliquary-key" = "archive-reliquary-key",
  "oubliette-reliquary-key" = "oubliette-reliquary-key",
  "cosmic-reliquary-key" = "cosmic-reliquary-key",
  "decaying-reliquary-key" = "decaying-reliquary-key",
  "divine-vessel" = "divine-vessel",
}

/** All currencies belonging to the group `MemoryLine` (Memory Lines) */
export enum MemoryLine {
  "alvas-memory-of-cascading-fortunes" = "alvas-memory-of-cascading-fortunes",
  "alvas-memory-of-reverse-incursion" = "alvas-memory-of-reverse-incursion",
  "einhars-memory-of-crystal-prisons" = "einhars-memory-of-crystal-prisons",
  "einhars-memory-of-the-sacred-grove" = "einhars-memory-of-the-sacred-grove",
  "kiracs-memory-of-phaaryl" = "kiracs-memory-of-phaaryl",
  "kiracs-memory-of-survivors-guilt" = "kiracs-memory-of-survivors-guilt",
  "nikos-memory-of-chasms" = "nikos-memory-of-chasms",
  "nikos-memory-of-demonic-onslaught" = "nikos-memory-of-demonic-onslaught",
  "nikos-memory-of-grasping-hands" = "nikos-memory-of-grasping-hands",
  "nikos-memory-of-tormented-souls" = "nikos-memory-of-tormented-souls",
}

/** All currencies belonging to the group `ScoutingReport` (Scouting Reports) */
export enum ScoutingReport {
  "singular-scouting-report" = "singular-scouting-report",
  "otherworldly-scouting-report" = "otherworldly-scouting-report",
  "comprehensive-scouting-report" = "comprehensive-scouting-report",
  "vaal-scouting-report" = "vaal-scouting-report",
  "delirious-scouting-report" = "delirious-scouting-report",
  "operatives-scouting-report" = "operatives-scouting-report",
  "blighted-scouting-report" = "blighted-scouting-report",
  "influenced-scouting-report" = "influenced-scouting-report",
  "explorers-scouting-report" = "explorers-scouting-report",
}

/** All currencies belonging to the group `Expedition` (Expedition Currency) */
export enum Expedition {
  astragali = "astragali",
  "exotic-coinage" = "exotic-coinage",
  "scrap-metal" = "scrap-metal",
  "burial-medallion" = "burial-medallion",
}

/** All currencies belonging to the group `DeliriumOrbs` (Delirium Orbs) */
export enum DeliriumOrbs {
  "fine-delirium-orb" = "fine-delirium-orb",
  "singular-delirium-orb" = "singular-delirium-orb",
  "thaumaturges-delirium-orb" = "thaumaturges-delirium-orb",
  "blacksmiths-delirium-orb" = "blacksmiths-delirium-orb",
  "armoursmiths-delirium-orb" = "armoursmiths-delirium-orb",
  "cartographers-delirium-orb" = "cartographers-delirium-orb",
  "jewellers-delirium-orb" = "jewellers-delirium-orb",
  "abyssal-delirium-orb" = "abyssal-delirium-orb",
  "kalguuran-delirium-orb" = "kalguuran-delirium-orb",
  "foreboding-delirium-orb" = "foreboding-delirium-orb",
  "obscured-delirium-orb" = "obscured-delirium-orb",
  "whispering-delirium-orb" = "whispering-delirium-orb",
  "fragmented-delirium-orb" = "fragmented-delirium-orb",
  "skittering-delirium-orb" = "skittering-delirium-orb",
  "fossilised-delirium-orb" = "fossilised-delirium-orb",
  "diviners-delirium-orb" = "diviners-delirium-orb",
  "delirium-orb" = "delirium-orb",
  "primal-delirium-orb" = "primal-delirium-orb",
  "imperial-delirium-orb" = "imperial-delirium-orb",
  "timeless-delirium-orb" = "timeless-delirium-orb",
  "blighted-delirium-orb" = "blighted-delirium-orb",
  "amorphous-delirium-orb" = "amorphous-delirium-orb",
}

/** All currencies belonging to the group `Catalysts` (Catalysts) */
export enum Catalysts {
  "turbulent-catalyst" = "turbulent-catalyst",
  "imbued-catalyst" = "imbued-catalyst",
  "abrasive-catalyst" = "abrasive-catalyst",
  "tempering-catalyst" = "tempering-catalyst",
  "fertile-catalyst" = "fertile-catalyst",
  "prismatic-catalyst" = "prismatic-catalyst",
  "intrinsic-catalyst" = "intrinsic-catalyst",
  "noxious-catalyst" = "noxious-catalyst",
  "accelerating-catalyst" = "accelerating-catalyst",
  "unstable-catalyst" = "unstable-catalyst",
}

/** All currencies belonging to the group `Oils` (Oils & Extractor) */
export enum Oils {
  "clear-oil" = "clear-oil",
  "sepia-oil" = "sepia-oil",
  "amber-oil" = "amber-oil",
  "verdant-oil" = "verdant-oil",
  "teal-oil" = "teal-oil",
  "azure-oil" = "azure-oil",
  "indigo-oil" = "indigo-oil",
  "violet-oil" = "violet-oil",
  "crimson-oil" = "crimson-oil",
  "black-oil" = "black-oil",
  "opalescent-oil" = "opalescent-oil",
  "silver-oil" = "silver-oil",
  "golden-oil" = "golden-oil",
  "tainted-oil" = "tainted-oil",
  "reflective-oil" = "reflective-oil",
  "oil-extractor" = "oil-extractor",
}

/** All currencies belonging to the group `Incubators` (Incubators) */
export enum Incubators {
  "whispering-incubator" = "whispering-incubator",
  "fine-incubator" = "fine-incubator",
  "singular-incubator" = "singular-incubator",
  "cartographers-incubator" = "cartographers-incubator",
  "otherworldly-incubator" = "otherworldly-incubator",
  "abyssal-incubator" = "abyssal-incubator",
  "fragmented-incubator" = "fragmented-incubator",
  "skittering-incubator" = "skittering-incubator",
  "infused-incubator" = "infused-incubator",
  "fossilised-incubator" = "fossilised-incubator",
  "kalguuran-incubator" = "kalguuran-incubator",
  "diviners-incubator" = "diviners-incubator",
  "primal-incubator" = "primal-incubator",
  "enchanted-incubator" = "enchanted-incubator",
  "geomancers-incubator" = "geomancers-incubator",
  "ornate-incubator" = "ornate-incubator",
  "time-lost-incubator" = "time-lost-incubator",
  "celestial-armoursmiths-incubator" = "celestial-armoursmiths-incubator",
  "celestial-blacksmiths-incubator" = "celestial-blacksmiths-incubator",
  "celestial-jewellers-incubator" = "celestial-jewellers-incubator",
  "eldritch-incubator" = "eldritch-incubator",
  "obscured-incubator" = "obscured-incubator",
  "foreboding-incubator" = "foreboding-incubator",
  "thaumaturges-incubator" = "thaumaturges-incubator",
  "mysterious-incubator" = "mysterious-incubator",
  "gemcutters-incubator" = "gemcutters-incubator",
  "feral-incubator" = "feral-incubator",
  "blighted-incubator" = "blighted-incubator",
  "morphing-incubator" = "morphing-incubator",
  "maddening-incubator" = "maddening-incubator",
}

/** All currencies belonging to the group `Scarabs` (Scarabs) */
export enum Scarabs {
  "rusted-breach-scarab" = "rusted-breach-scarab",
  "polished-breach-scarab" = "polished-breach-scarab",
  "gilded-breach-scarab" = "gilded-breach-scarab",
  "jewelled-breach-scarab" = "jewelled-breach-scarab",
  "rusted-cartography-scarab" = "rusted-cartography-scarab",
  "polished-cartography-scarab" = "polished-cartography-scarab",
  "gilded-cartography-scarab" = "gilded-cartography-scarab",
  "jewelled-cartography-scarab" = "jewelled-cartography-scarab",
  "rusted-reliquary-scarab" = "rusted-reliquary-scarab",
  "polished-reliquary-scarab" = "polished-reliquary-scarab",
  "gilded-reliquary-scarab" = "gilded-reliquary-scarab",
  "jewelled-reliquary-scarab" = "jewelled-reliquary-scarab",
  "rusted-bestiary-scarab" = "rusted-bestiary-scarab",
  "polished-bestiary-scarab" = "polished-bestiary-scarab",
  "gilded-bestiary-scarab" = "gilded-bestiary-scarab",
  "jewelled-bestiary-scarab" = "jewelled-bestiary-scarab",
  "farric-lure" = "farric-lure",
  "saqawine-lure" = "saqawine-lure",
  "fenumal-lure" = "fenumal-lure",
  "craicic-lure" = "craicic-lure",
  "rusted-shaper-scarab" = "rusted-shaper-scarab",
  "polished-shaper-scarab" = "polished-shaper-scarab",
  "gilded-shaper-scarab" = "gilded-shaper-scarab",
  "jewelled-shaper-scarab" = "jewelled-shaper-scarab",
  "rusted-elder-scarab" = "rusted-elder-scarab",
  "polished-elder-scarab" = "polished-elder-scarab",
  "gilded-elder-scarab" = "gilded-elder-scarab",
  "jewelled-elder-scarab" = "jewelled-elder-scarab",
  "rusted-sulphite-scarab" = "rusted-sulphite-scarab",
  "polished-sulphite-scarab" = "polished-sulphite-scarab",
  "gilded-sulphite-scarab" = "gilded-sulphite-scarab",
  "jewelled-sulphite-scarab" = "jewelled-sulphite-scarab",
  "rusted-divination-scarab" = "rusted-divination-scarab",
  "polished-divination-scarab" = "polished-divination-scarab",
  "gilded-divination-scarab" = "gilded-divination-scarab",
  "jewelled-divination-scarab" = "jewelled-divination-scarab",
  "rusted-torment-scarab" = "rusted-torment-scarab",
  "polished-torment-scarab" = "polished-torment-scarab",
  "gilded-torment-scarab" = "gilded-torment-scarab",
  "jewelled-torment-scarab" = "jewelled-torment-scarab",
  "rusted-ambush-scarab" = "rusted-ambush-scarab",
  "polished-ambush-scarab" = "polished-ambush-scarab",
  "gilded-ambush-scarab" = "gilded-ambush-scarab",
  "jewelled-ambush-scarab" = "jewelled-ambush-scarab",
  "rusted-harbinger-scarab" = "rusted-harbinger-scarab",
  "polished-harbinger-scarab" = "polished-harbinger-scarab",
  "gilded-harbinger-scarab" = "gilded-harbinger-scarab",
  "jewelled-harbinger-scarab" = "jewelled-harbinger-scarab",
  "rusted-expedition-scarab" = "rusted-expedition-scarab",
  "polished-expedition-scarab" = "polished-expedition-scarab",
  "gilded-expedition-scarab" = "gilded-expedition-scarab",
  "winged-expedition-scarab" = "winged-expedition-scarab",
  "rusted-legion-scarab" = "rusted-legion-scarab",
  "polished-legion-scarab" = "polished-legion-scarab",
  "gilded-legion-scarab" = "gilded-legion-scarab",
  "jewelled-legion-scarab" = "jewelled-legion-scarab",
  "rusted-metamorph-scarab" = "rusted-metamorph-scarab",
  "polished-metamorph-scarab" = "polished-metamorph-scarab",
  "gilded-metamorph-scarab" = "gilded-metamorph-scarab",
  "jewelled-metamorph-scarab" = "jewelled-metamorph-scarab",
  "rusted-blight-scarab" = "rusted-blight-scarab",
  "polished-blight-scarab" = "polished-blight-scarab",
  "gilded-blight-scarab" = "gilded-blight-scarab",
  "winged-blight-scarab" = "winged-blight-scarab",
  "rusted-abyss-scarab" = "rusted-abyss-scarab",
  "polished-abyss-scarab" = "polished-abyss-scarab",
  "gilded-abyss-scarab" = "gilded-abyss-scarab",
  "winged-abyss-scarab" = "winged-abyss-scarab",
}

/** All currencies belonging to the group `DelveResonators` (Delve Resonators) */
export enum DelveResonators {
  "primitive-chaotic-resonator" = "primitive-chaotic-resonator",
  "potent-chaotic-resonator" = "potent-chaotic-resonator",
  "powerful-chaotic-resonator" = "powerful-chaotic-resonator",
  "prime-chaotic-resonator" = "prime-chaotic-resonator",
}

/** All currencies belonging to the group `DelveFossils` (Delve Fossils) */
export enum DelveFossils {
  "scorched-fossil" = "scorched-fossil",
  "frigid-fossil" = "frigid-fossil",
  "metallic-fossil" = "metallic-fossil",
  "jagged-fossil" = "jagged-fossil",
  "aberrant-fossil" = "aberrant-fossil",
  "pristine-fossil" = "pristine-fossil",
  "dense-fossil" = "dense-fossil",
  "corroded-fossil" = "corroded-fossil",
  "prismatic-fossil" = "prismatic-fossil",
  "aetheric-fossil" = "aetheric-fossil",
  "serrated-fossil" = "serrated-fossil",
  "lucent-fossil" = "lucent-fossil",
  "shuddering-fossil" = "shuddering-fossil",
  "bound-fossil" = "bound-fossil",
  "perfect-fossil" = "perfect-fossil",
  "deft-fossil" = "deft-fossil",
  "fundamental-fossil" = "fundamental-fossil",
  "faceted-fossil" = "faceted-fossil",
  "bloodstained-fossil" = "bloodstained-fossil",
  "hollow-fossil" = "hollow-fossil",
  "fractured-fossil" = "fractured-fossil",
  "glyphic-fossil" = "glyphic-fossil",
  "tangled-fossil" = "tangled-fossil",
  "sanctified-fossil" = "sanctified-fossil",
  "gilded-fossil" = "gilded-fossil",
}

/** All currencies belonging to the group `Essences` (Essences) */
export enum Essences {
  "whispering-essence-of-hatred" = "whispering-essence-of-hatred",
  "muttering-essence-of-hatred" = "muttering-essence-of-hatred",
  "weeping-essence-of-hatred" = "weeping-essence-of-hatred",
  "wailing-essence-of-hatred" = "wailing-essence-of-hatred",
  "screaming-essence-of-hatred" = "screaming-essence-of-hatred",
  "shrieking-essence-of-hatred" = "shrieking-essence-of-hatred",
  "deafening-essence-of-hatred" = "deafening-essence-of-hatred",
  "whispering-essence-of-woe" = "whispering-essence-of-woe",
  "muttering-essence-of-woe" = "muttering-essence-of-woe",
  "weeping-essence-of-woe" = "weeping-essence-of-woe",
  "wailing-essence-of-woe" = "wailing-essence-of-woe",
  "screaming-essence-of-woe" = "screaming-essence-of-woe",
  "shrieking-essence-of-woe" = "shrieking-essence-of-woe",
  "deafening-essence-of-woe" = "deafening-essence-of-woe",
  "whispering-essence-of-greed" = "whispering-essence-of-greed",
  "muttering-essence-of-greed" = "muttering-essence-of-greed",
  "weeping-essence-of-greed" = "weeping-essence-of-greed",
  "wailing-essence-of-greed" = "wailing-essence-of-greed",
  "screaming-essence-of-greed" = "screaming-essence-of-greed",
  "shrieking-essence-of-greed" = "shrieking-essence-of-greed",
  "deafening-essence-of-greed" = "deafening-essence-of-greed",
  "whispering-essence-of-contempt" = "whispering-essence-of-contempt",
  "muttering-essence-of-contempt" = "muttering-essence-of-contempt",
  "weeping-essence-of-contempt" = "weeping-essence-of-contempt",
  "wailing-essence-of-contempt" = "wailing-essence-of-contempt",
  "screaming-essence-of-contempt" = "screaming-essence-of-contempt",
  "shrieking-essence-of-contempt" = "shrieking-essence-of-contempt",
  "deafening-essence-of-contempt" = "deafening-essence-of-contempt",
  "muttering-essence-of-sorrow" = "muttering-essence-of-sorrow",
  "weeping-essence-of-sorrow" = "weeping-essence-of-sorrow",
  "wailing-essence-of-sorrow" = "wailing-essence-of-sorrow",
  "screaming-essence-of-sorrow" = "screaming-essence-of-sorrow",
  "shrieking-essence-of-sorrow" = "shrieking-essence-of-sorrow",
  "deafening-essence-of-sorrow" = "deafening-essence-of-sorrow",
  "muttering-essence-of-anger" = "muttering-essence-of-anger",
  "weeping-essence-of-anger" = "weeping-essence-of-anger",
  "wailing-essence-of-anger" = "wailing-essence-of-anger",
  "screaming-essence-of-anger" = "screaming-essence-of-anger",
  "shrieking-essence-of-anger" = "shrieking-essence-of-anger",
  "deafening-essence-of-anger" = "deafening-essence-of-anger",
  "muttering-essence-of-torment" = "muttering-essence-of-torment",
  "weeping-essence-of-torment" = "weeping-essence-of-torment",
  "wailing-essence-of-torment" = "wailing-essence-of-torment",
  "screaming-essence-of-torment" = "screaming-essence-of-torment",
  "shrieking-essence-of-torment" = "shrieking-essence-of-torment",
  "deafening-essence-of-torment" = "deafening-essence-of-torment",
  "muttering-essence-of-fear" = "muttering-essence-of-fear",
  "weeping-essence-of-fear" = "weeping-essence-of-fear",
  "wailing-essence-of-fear" = "wailing-essence-of-fear",
  "screaming-essence-of-fear" = "screaming-essence-of-fear",
  "shrieking-essence-of-fear" = "shrieking-essence-of-fear",
  "deafening-essence-of-fear" = "deafening-essence-of-fear",
  "weeping-essence-of-suffering" = "weeping-essence-of-suffering",
  "wailing-essence-of-suffering" = "wailing-essence-of-suffering",
  "screaming-essence-of-suffering" = "screaming-essence-of-suffering",
  "shrieking-essence-of-suffering" = "shrieking-essence-of-suffering",
  "deafening-essence-of-suffering" = "deafening-essence-of-suffering",
  "weeping-essence-of-rage" = "weeping-essence-of-rage",
  "wailing-essence-of-rage" = "wailing-essence-of-rage",
  "screaming-essence-of-rage" = "screaming-essence-of-rage",
  "shrieking-essence-of-rage" = "shrieking-essence-of-rage",
  "deafening-essence-of-rage" = "deafening-essence-of-rage",
  "weeping-essence-of-wrath" = "weeping-essence-of-wrath",
  "wailing-essence-of-wrath" = "wailing-essence-of-wrath",
  "screaming-essence-of-wrath" = "screaming-essence-of-wrath",
  "shrieking-essence-of-wrath" = "shrieking-essence-of-wrath",
  "deafening-essence-of-wrath" = "deafening-essence-of-wrath",
  "weeping-essence-of-doubt" = "weeping-essence-of-doubt",
  "wailing-essence-of-doubt" = "wailing-essence-of-doubt",
  "screaming-essence-of-doubt" = "screaming-essence-of-doubt",
  "shrieking-essence-of-doubt" = "shrieking-essence-of-doubt",
  "deafening-essence-of-doubt" = "deafening-essence-of-doubt",
  "wailing-essence-of-anguish" = "wailing-essence-of-anguish",
  "screaming-essence-of-anguish" = "screaming-essence-of-anguish",
  "shrieking-essence-of-anguish" = "shrieking-essence-of-anguish",
  "deafening-essence-of-anguish" = "deafening-essence-of-anguish",
  "wailing-essence-of-loathing" = "wailing-essence-of-loathing",
  "screaming-essence-of-loathing" = "screaming-essence-of-loathing",
  "shrieking-essence-of-loathing" = "shrieking-essence-of-loathing",
  "deafening-essence-of-loathing" = "deafening-essence-of-loathing",
  "wailing-essence-of-spite" = "wailing-essence-of-spite",
  "screaming-essence-of-spite" = "screaming-essence-of-spite",
  "shrieking-essence-of-spite" = "shrieking-essence-of-spite",
  "deafening-essence-of-spite" = "deafening-essence-of-spite",
  "wailing-essence-of-zeal" = "wailing-essence-of-zeal",
  "screaming-essence-of-zeal" = "screaming-essence-of-zeal",
  "shrieking-essence-of-zeal" = "shrieking-essence-of-zeal",
  "deafening-essence-of-zeal" = "deafening-essence-of-zeal",
  "screaming-essence-of-misery" = "screaming-essence-of-misery",
  "shrieking-essence-of-misery" = "shrieking-essence-of-misery",
  "deafening-essence-of-misery" = "deafening-essence-of-misery",
  "screaming-essence-of-dread" = "screaming-essence-of-dread",
  "shrieking-essence-of-dread" = "shrieking-essence-of-dread",
  "deafening-essence-of-dread" = "deafening-essence-of-dread",
  "screaming-essence-of-scorn" = "screaming-essence-of-scorn",
  "shrieking-essence-of-scorn" = "shrieking-essence-of-scorn",
  "deafening-essence-of-scorn" = "deafening-essence-of-scorn",
  "screaming-essence-of-envy" = "screaming-essence-of-envy",
  "shrieking-essence-of-envy" = "shrieking-essence-of-envy",
  "deafening-essence-of-envy" = "deafening-essence-of-envy",
  "essence-of-hysteria" = "essence-of-hysteria",
  "essence-of-insanity" = "essence-of-insanity",
  "essence-of-horror" = "essence-of-horror",
  "essence-of-delirium" = "essence-of-delirium",
  "remnant-of-corruption" = "remnant-of-corruption",
}

/** All currencies belonging to the group `Cards` (Cards) */
export enum Cards {
  "a-dab-of-ink" = "a-dab-of-ink",
  "a-familiar-call" = "a-familiar-call",
  "a-fate-worse-than-death" = "a-fate-worse-than-death",
  "a-modest-request" = "a-modest-request",
  "a-mothers-parting-gift" = "a-mothers-parting-gift",
  "a-note-in-the-wind" = "a-note-in-the-wind",
  "a-sea-of-blue" = "a-sea-of-blue",
  "a-stone-perfected" = "a-stone-perfected",
  "abandoned-wealth" = "abandoned-wealth",
  acclimatisation = "acclimatisation",
  "akils-prophecy" = "akils-prophecy",
  "alluring-bounty" = "alluring-bounty",
  "alone-in-the-darkness" = "alone-in-the-darkness",
  "altered-perception" = "altered-perception",
  "ambitious-obsession" = "ambitious-obsession",
  "anarchys-price" = "anarchys-price",
  "arrogance-of-the-vaal" = "arrogance-of-the-vaal",
  "assassins-favour" = "assassins-favour",
  "astral-protection" = "astral-protection",
  "atziris-arsenal" = "atziris-arsenal",
  audacity = "audacity",
  "azure-rage" = "azure-rage",
  "azyrans-reward" = "azyrans-reward",
  "baited-expectations" = "baited-expectations",
  "beauty-through-death" = "beauty-through-death",
  bijoux = "bijoux",
  "birth-of-the-three" = "birth-of-the-three",
  "blessing-of-god" = "blessing-of-god",
  "blind-venture" = "blind-venture",
  "boon-of-justice" = "boon-of-justice",
  "boon-of-the-first-ones" = "boon-of-the-first-ones",
  "boundless-realms" = "boundless-realms",
  "bowyers-dream" = "bowyers-dream",
  "broken-promises" = "broken-promises",
  "broken-truce" = "broken-truce",
  "brotherhood-in-exile" = "brotherhood-in-exile",
  "brothers-stash" = "brothers-stash",
  "brush-paint-and-palette" = "brush-paint-and-palette",
  "buried-treasure" = "buried-treasure",
  "burning-blood" = "burning-blood",
  "call-to-the-first-ones" = "call-to-the-first-ones",
  "camerias-cut" = "camerias-cut",
  "cartographers-delight" = "cartographers-delight",
  "chaotic-disposition" = "chaotic-disposition",
  "chasing-risk" = "chasing-risk",
  checkmate = "checkmate",
  "choking-guilt" = "choking-guilt",
  "costly-curio" = "costly-curio",
  "council-of-cats" = "council-of-cats",
  "coveted-possession" = "coveted-possession",
  "cursed-words" = "cursed-words",
  "dark-dreams" = "dark-dreams",
  "dark-temptation" = "dark-temptation",
  "darker-half" = "darker-half",
  "deadly-joy" = "deadly-joy",
  death = "death",
  "deathly-designs" = "deathly-designs",
  dementophobia = "dementophobia",
  "demigods-wager" = "demigods-wager",
  "desecrated-virtue" = "desecrated-virtue",
  "desperate-crusade" = "desperate-crusade",
  "destined-to-crumble" = "destined-to-crumble",
  "diallas-subjugation" = "diallas-subjugation",
  disdain = "disdain",
  "divine-justice" = "divine-justice",
  "doedres-madness" = "doedres-madness",
  "doryanis-epiphany" = "doryanis-epiphany",
  "draped-in-dreams" = "draped-in-dreams",
  duality = "duality",
  "dying-anguish" = "dying-anguish",
  "dying-light" = "dying-light",
  "earth-drinker" = "earth-drinker",
  "echoes-of-love" = "echoes-of-love",
  "emperor-of-purity" = "emperor-of-purity",
  "emperors-luck" = "emperors-luck",
  "endless-night" = "endless-night",
  "etched-in-blood" = "etched-in-blood",
  "eternal-bonds" = "eternal-bonds",
  "fateful-meeting" = "fateful-meeting",
  "forbidden-power" = "forbidden-power",
  friendship = "friendship",
  "from-bone-to-ashes" = "from-bone-to-ashes",
  "further-invention" = "further-invention",
  "gemcutters-mercy" = "gemcutters-mercy",
  "gemcutters-promise" = "gemcutters-promise",
  "gift-of-asenath" = "gift-of-asenath",
  "gift-of-the-gemling-queen" = "gift-of-the-gemling-queen",
  "glimmer-of-hope" = "glimmer-of-hope",
  "grave-knowledge" = "grave-knowledge",
  "guardians-challenge" = "guardians-challenge",
  "harmony-of-souls" = "harmony-of-souls",
  "haunting-shadows" = "haunting-shadows",
  "her-mask" = "her-mask",
  heterochromia = "heterochromia",
  home = "home",
  "hope-card" = "hope-card",
  "house-of-mirrors" = "house-of-mirrors",
  hubris = "hubris",
  humility = "humility",
  "hunters-resolve" = "hunters-resolve",
  "hunters-reward" = "hunters-reward",
  "immortal-resolve" = "immortal-resolve",
  "imperfect-memories" = "imperfect-memories",
  "imperial-legacy" = "imperial-legacy",
  "jack-in-the-box" = "jack-in-the-box",
  "judging-voices" = "judging-voices",
  "justified-ambition" = "justified-ambition",
  "keepers-corruption" = "keepers-corruption",
  "lachrymal-necrosis" = "lachrymal-necrosis",
  "lantadors-lost-love" = "lantadors-lost-love",
  "last-hope" = "last-hope",
  "left-to-fate" = "left-to-fate",
  "lethean-temptation" = "lethean-temptation",
  "light-and-truth" = "light-and-truth",
  "lingering-remnants" = "lingering-remnants",
  "lost-worlds" = "lost-worlds",
  "love-through-ice" = "love-through-ice",
  loyalty = "loyalty",
  "luck-of-the-vaal" = "luck-of-the-vaal",
  "lucky-connections" = "lucky-connections",
  "lucky-deck" = "lucky-deck",
  "luminous-trove" = "luminous-trove",
  "lysahs-respite" = "lysahs-respite",
  "magnum-opus" = "magnum-opus",
  "mawr-blaidd" = "mawr-blaidd",
  "merciless-armament" = "merciless-armament",
  "might-is-right" = "might-is-right",
  "misery-in-darkness" = "misery-in-darkness",
  mitts = "mitts",
  monochrome = "monochrome",
  "more-is-never-enough" = "more-is-never-enough",
  "no-traces" = "no-traces",
  "nooks-crown" = "nooks-crown",
  "parasitic-passengers" = "parasitic-passengers",
  "peaceful-moments" = "peaceful-moments",
  perfection = "perfection",
  prejudice = "prejudice",
  "pride-before-the-fall" = "pride-before-the-fall",
  "pride-of-the-first-ones" = "pride-of-the-first-ones",
  "prometheus-armoury" = "prometheus-armoury",
  prosperity = "prosperity",
  "rain-of-chaos" = "rain-of-chaos",
  "rain-tempter" = "rain-tempter",
  rats = "rats",
  rebirth = "rebirth",
  "rebirth-and-renewal" = "rebirth-and-renewal",
  "reckless-ambition" = "reckless-ambition",
  remembrance = "remembrance",
  "sambodhis-vow" = "sambodhis-vow",
  "sambodhis-wisdom" = "sambodhis-wisdom",
  "scholar-of-the-seas" = "scholar-of-the-seas",
  "seven-years-bad-luck" = "seven-years-bad-luck",
  "shard-of-fate" = "shard-of-fate",
  "silence-and-frost" = "silence-and-frost",
  "societys-remorse" = "societys-remorse",
  "something-dark" = "something-dark",
  "squandered-prosperity" = "squandered-prosperity",
  "struck-by-lightning" = "struck-by-lightning",
  "succor-of-the-sinless" = "succor-of-the-sinless",
  "terrible-secret-of-space" = "terrible-secret-of-space",
  "the-academic" = "the-academic",
  "the-admirer" = "the-admirer",
  "the-adventuring-spirit" = "the-adventuring-spirit",
  "the-aesthete" = "the-aesthete",
  "the-apothecary" = "the-apothecary",
  "the-archmages-right-hand" = "the-archmages-right-hand",
  "the-arena-champion" = "the-arena-champion",
  "the-army-of-blood" = "the-army-of-blood",
  "the-artist" = "the-artist",
  "the-aspirant" = "the-aspirant",
  "the-astromancer" = "the-astromancer",
  "the-avenger" = "the-avenger",
  "the-awakened" = "the-awakened",
  "the-bargain" = "the-bargain",
  "the-battle-born" = "the-battle-born",
  "the-bear-woman" = "the-bear-woman",
  "the-beast" = "the-beast",
  "the-betrayal" = "the-betrayal",
  "the-bitter-blossom" = "the-bitter-blossom",
  "the-blazing-fire" = "the-blazing-fire",
  "the-blessing-of-moosh" = "the-blessing-of-moosh",
  "the-body" = "the-body",
  "the-bones" = "the-bones",
  "the-brawny-battle-mage" = "the-brawny-battle-mage",
  "the-breach" = "the-breach",
  "the-brittle-emperor" = "the-brittle-emperor",
  "the-cache" = "the-cache",
  "the-cacophony" = "the-cacophony",
  "the-calling" = "the-calling",
  "the-card-sharp" = "the-card-sharp",
  "the-carrion-crow" = "the-carrion-crow",
  "the-cartographer" = "the-cartographer",
  "the-cataclysm" = "the-cataclysm",
  "the-catalyst" = "the-catalyst",
  "the-catch" = "the-catch",
  "the-celestial-justicar" = "the-celestial-justicar",
  "the-celestial-stone" = "the-celestial-stone",
  "the-chains-that-bind" = "the-chains-that-bind",
  "the-cheater" = "the-cheater",
  "the-chosen" = "the-chosen",
  "the-coming-storm" = "the-coming-storm",
  "the-conduit" = "the-conduit",
  "the-craving" = "the-craving",
  "the-cursed-king" = "the-cursed-king",
  "the-damned" = "the-damned",
  "the-dapper-prodigy" = "the-dapper-prodigy",
  "the-dark-mage" = "the-dark-mage",
  "the-darkest-dream" = "the-darkest-dream",
  "the-deal" = "the-deal",
  "the-deceiver" = "the-deceiver",
  "the-deep-ones" = "the-deep-ones",
  "the-demon" = "the-demon",
  "the-demoness" = "the-demoness",
  "the-destination" = "the-destination",
  "the-devastator" = "the-devastator",
  "the-doctor" = "the-doctor",
  "the-doppelganger" = "the-doppelganger",
  "the-dragon" = "the-dragon",
  "the-dragons-heart" = "the-dragons-heart",
  "the-dreamer" = "the-dreamer",
  "the-dreamland" = "the-dreamland",
  "the-drunken-aristocrat" = "the-drunken-aristocrat",
  "the-dungeon-master" = "the-dungeon-master",
  "the-easy-stroll" = "the-easy-stroll",
  "the-eldritch-decay" = "the-eldritch-decay",
  "the-emptiness" = "the-emptiness",
  "the-encroaching-darkness" = "the-encroaching-darkness",
  "the-endless-darkness" = "the-endless-darkness",
  "the-endurance" = "the-endurance",
  "the-enforcer" = "the-enforcer",
  "the-enlightened" = "the-enlightened",
  "the-enthusiasts" = "the-enthusiasts",
  "the-escape" = "the-escape",
  "the-eternal-war" = "the-eternal-war",
  "the-ethereal" = "the-ethereal",
  "the-explorer" = "the-explorer",
  "the-eye-of-terror" = "the-eye-of-terror",
  "the-eye-of-the-dragon" = "the-eye-of-the-dragon",
  "the-fathomless-depths" = "the-fathomless-depths",
  "the-feast" = "the-feast",
  "the-fiend" = "the-fiend",
  "the-fishmonger" = "the-fishmonger",
  "the-fletcher" = "the-fletcher",
  "the-floras-gift" = "the-floras-gift",
  "the-fool" = "the-fool",
  "the-forgotten-treasure" = "the-forgotten-treasure",
  "the-formless-sea" = "the-formless-sea",
  "the-forsaken" = "the-forsaken",
  "the-forward-gaze" = "the-forward-gaze",
  "the-fox" = "the-fox",
  "the-fox-in-the-brambles" = "the-fox-in-the-brambles",
  "the-gambler" = "the-gambler",
  "the-garish-power" = "the-garish-power",
  "the-gemcutter" = "the-gemcutter",
  "the-gentleman" = "the-gentleman",
  "the-gladiator" = "the-gladiator",
  "the-golden-era" = "the-golden-era",
  "the-greatest-intentions" = "the-greatest-intentions",
  "the-gulf" = "the-gulf",
  "the-hale-heart" = "the-hale-heart",
  "the-harvester" = "the-harvester",
  "the-hermit" = "the-hermit",
  "the-heroic-shot" = "the-heroic-shot",
  "the-hive-of-knowledge" = "the-hive-of-knowledge",
  "the-hoarder" = "the-hoarder",
  "the-hook" = "the-hook",
  "the-hunger" = "the-hunger",
  "the-immortal" = "the-immortal",
  "the-incantation" = "the-incantation",
  "the-innocent" = "the-innocent",
  "the-inoculated" = "the-inoculated",
  "the-insatiable" = "the-insatiable",
  "the-inventor" = "the-inventor",
  "the-iron-bard" = "the-iron-bard",
  "the-jester" = "the-jester",
  "the-jewellers-boon" = "the-jewellers-boon",
  "the-journalist" = "the-journalist",
  "the-journey" = "the-journey",
  "the-kings-blade" = "the-kings-blade",
  "the-kings-heart" = "the-kings-heart",
  "the-landing" = "the-landing",
  "the-last-one-standing" = "the-last-one-standing",
  "the-last-supper" = "the-last-supper",
  "the-leviathan" = "the-leviathan",
  "the-lich" = "the-lich",
  "the-life-thief" = "the-life-thief",
  "the-lion" = "the-lion",
  "the-long-con" = "the-long-con",
  "the-long-watch" = "the-long-watch",
  "the-lord-in-black" = "the-lord-in-black",
  "the-lord-of-celebration" = "the-lord-of-celebration",
  "the-lover" = "the-lover",
  "the-lunaris-priestess" = "the-lunaris-priestess",
  "the-mad-king" = "the-mad-king",
  "the-magma-crab" = "the-magma-crab",
  "the-master" = "the-master",
  "the-master-artisan" = "the-master-artisan",
  "the-mayor" = "the-mayor",
  "the-mercenary" = "the-mercenary",
  "the-messenger" = "the-messenger",
  "the-metalsmiths-gift" = "the-metalsmiths-gift",
  "the-minds-eyes" = "the-minds-eyes",
  "the-mountain" = "the-mountain",
  "the-nurse" = "the-nurse",
  "the-oath" = "the-oath",
  "the-obscured" = "the-obscured",
  "the-offering" = "the-offering",
  "the-offspring" = "the-offspring",
  "the-old-man" = "the-old-man",
  "the-one-that-got-away" = "the-one-that-got-away",
  "the-one-with-all" = "the-one-with-all",
  "the-opulent" = "the-opulent",
  "the-pack-leader" = "the-pack-leader",
  "the-pact" = "the-pact",
  "the-patient" = "the-patient",
  "the-penitent" = "the-penitent",
  "the-poet" = "the-poet",
  "the-polymath" = "the-polymath",
  "the-porcupine" = "the-porcupine",
  "the-price-of-devotion" = "the-price-of-devotion",
  "the-price-of-loyalty" = "the-price-of-loyalty",
  "the-price-of-prescience" = "the-price-of-prescience",
  "the-price-of-protection" = "the-price-of-protection",
  "the-primordial" = "the-primordial",
  "the-prince-of-darkness" = "the-prince-of-darkness",
  "the-professor" = "the-professor",
  "the-progeny-of-lunaris" = "the-progeny-of-lunaris",
  "the-puzzle" = "the-puzzle",
  "the-queen" = "the-queen",
  "the-rabbits-foot" = "the-rabbits-foot",
  "the-rabid-rhoa" = "the-rabid-rhoa",
  "the-realm" = "the-realm",
  "the-risk" = "the-risk",
  "the-rite-of-elements" = "the-rite-of-elements",
  "the-road-to-power" = "the-road-to-power",
  "the-ruthless-ceinture" = "the-ruthless-ceinture",
  "the-sacrifice" = "the-sacrifice",
  "the-saints-treasure" = "the-saints-treasure",
  "the-samurais-eye" = "the-samurais-eye",
  "the-scarred-meadow" = "the-scarred-meadow",
  "the-scavenger" = "the-scavenger",
  "the-scholar" = "the-scholar",
  "the-scout-card" = "the-scout-card",
  "the-seeker" = "the-seeker",
  "the-sephirot" = "the-sephirot",
  "the-shepherds-sandals" = "the-shepherds-sandals",
  "the-shieldbearer" = "the-shieldbearer",
  "the-shortcut" = "the-shortcut",
  "the-side-quest" = "the-side-quest",
  "the-sigil" = "the-sigil",
  "the-siren" = "the-siren",
  "the-skeleton" = "the-skeleton",
  "the-soul" = "the-soul",
  "the-spark-and-the-flame" = "the-spark-and-the-flame",
  "the-spoiled-prince" = "the-spoiled-prince",
  "the-standoff" = "the-standoff",
  "the-stormcaller" = "the-stormcaller",
  "the-strategist" = "the-strategist",
  "the-summoner" = "the-summoner",
  "the-sun" = "the-sun",
  "the-surgeon" = "the-surgeon",
  "the-surveyor" = "the-surveyor",
  "the-survivalist" = "the-survivalist",
  "the-sustenance" = "the-sustenance",
  "the-sword-kings-salute" = "the-sword-kings-salute",
  "the-thaumaturgist" = "the-thaumaturgist",
  "the-throne" = "the-throne",
  "the-tinkerers-table" = "the-tinkerers-table",
  "the-tireless-extractor" = "the-tireless-extractor",
  "the-tower" = "the-tower",
  "the-traitor" = "the-traitor",
  "the-transformation" = "the-transformation",
  "the-trial" = "the-trial",
  "the-tumbleweed" = "the-tumbleweed",
  "the-twilight-moon" = "the-twilight-moon",
  "the-twins" = "the-twins",
  "the-tyrant" = "the-tyrant",
  "the-undaunted" = "the-undaunted",
  "the-undisputed" = "the-undisputed",
  "the-unexpected-prize" = "the-unexpected-prize",
  "the-union" = "the-union",
  "the-valkyrie" = "the-valkyrie",
  "the-valley-of-steel-boxes" = "the-valley-of-steel-boxes",
  "the-vast" = "the-vast",
  "the-visionary" = "the-visionary",
  "the-void" = "the-void",
  "the-warden" = "the-warden",
  "the-warlord" = "the-warlord",
  "the-watcher" = "the-watcher",
  "the-web" = "the-web",
  "the-white-knight" = "the-white-knight",
  "the-whiteout" = "the-whiteout",
  "the-wilted-rose" = "the-wilted-rose",
  "the-wind" = "the-wind",
  "the-witch" = "the-witch",
  "the-wolf" = "the-wolf",
  "the-wolfs-legacy" = "the-wolfs-legacy",
  "the-wolfs-shadow" = "the-wolfs-shadow",
  "the-wolven-kings-bite" = "the-wolven-kings-bite",
  "the-wolverine" = "the-wolverine",
  "the-world-eater" = "the-world-eater",
  "the-wrath" = "the-wrath",
  "the-wretched" = "the-wretched",
  "thirst-for-knowledge" = "thirst-for-knowledge",
  "three-faces-in-the-dark" = "three-faces-in-the-dark",
  "three-voices" = "three-voices",
  "thunderous-skies" = "thunderous-skies",
  "time-lost-relic" = "time-lost-relic",
  tranquillity = "tranquillity",
  "treasure-hunter" = "treasure-hunter",
  triskaidekaphobia = "triskaidekaphobia",
  "turn-the-other-cheek" = "turn-the-other-cheek",
  unchained = "unchained",
  "underground-forest" = "underground-forest",
  "unrequited-love" = "unrequited-love",
  vanity = "vanity",
  "vile-power" = "vile-power",
  "vinias-token" = "vinias-token",
  "void-of-the-elements" = "void-of-the-elements",
  "volatile-power" = "volatile-power",
  "wealth-and-power" = "wealth-and-power",
  "winters-embrace" = "winters-embrace",
}

/** All currencies belonging to the group `MapsTier1` (Maps (Tier 1)) */
export enum MapsTier1 {
  "frozen-cabins-map-tier-1" = "frozen-cabins-map-tier-1",
  "overgrown-ruin-map-tier-1" = "overgrown-ruin-map-tier-1",
  "strand-map-tier-1" = "strand-map-tier-1",
  "terrace-map-tier-1" = "terrace-map-tier-1",
}

/** All currencies belonging to the group `MapsTier2` (Maps (Tier 2)) */
export enum MapsTier2 {
  "bramble-valley-map-tier-2" = "bramble-valley-map-tier-2",
  "carcass-map-tier-2" = "carcass-map-tier-2",
  "colosseum-map-tier-2" = "colosseum-map-tier-2",
  "crimson-temple-map-tier-2" = "crimson-temple-map-tier-2",
  "dark-forest-map-tier-2" = "dark-forest-map-tier-2",
  "excavation-map-tier-2" = "excavation-map-tier-2",
  "moon-temple-map-tier-2" = "moon-temple-map-tier-2",
  "thicket-map-tier-2" = "thicket-map-tier-2",
}

/** All currencies belonging to the group `MapsTier3` (Maps (Tier 3)) */
export enum MapsTier3 {
  "bone-crypt-map-tier-3" = "bone-crypt-map-tier-3",
  "caldera-map-tier-3" = "caldera-map-tier-3",
  "cells-map-tier-3" = "cells-map-tier-3",
  "defiled-cathedral-map-tier-3" = "defiled-cathedral-map-tier-3",
  "factory-map-tier-3" = "factory-map-tier-3",
  "museum-map-tier-3" = "museum-map-tier-3",
  "park-map-tier-3" = "park-map-tier-3",
  "waterways-map-tier-3" = "waterways-map-tier-3",
}

/** All currencies belonging to the group `MapsTier4` (Maps (Tier 4)) */
export enum MapsTier4 {
  "atoll-map-tier-4" = "atoll-map-tier-4",
  "chateau-map-tier-4" = "chateau-map-tier-4",
  "dungeon-map-tier-4" = "dungeon-map-tier-4",
  "frozen-cabins-map-tier-4" = "frozen-cabins-map-tier-4",
  "laboratory-map-tier-4" = "laboratory-map-tier-4",
  "overgrown-ruin-map-tier-4" = "overgrown-ruin-map-tier-4",
  "phantasmagoria-map-tier-4" = "phantasmagoria-map-tier-4",
  "primordial-pool-map-tier-4" = "primordial-pool-map-tier-4",
  "shore-map-tier-4" = "shore-map-tier-4",
  "strand-map-tier-4" = "strand-map-tier-4",
  "terrace-map-tier-4" = "terrace-map-tier-4",
  "vaal-pyramid-map-tier-4" = "vaal-pyramid-map-tier-4",
}

/** All currencies belonging to the group `MapsTier5` (Maps (Tier 5)) */
export enum MapsTier5 {
  "acid-caverns-map-tier-5" = "acid-caverns-map-tier-5",
  "bramble-valley-map-tier-5" = "bramble-valley-map-tier-5",
  "carcass-map-tier-5" = "carcass-map-tier-5",
  "colosseum-map-tier-5" = "colosseum-map-tier-5",
  "coral-ruins-map-tier-5" = "coral-ruins-map-tier-5",
  "crater-map-tier-5" = "crater-map-tier-5",
  "crimson-temple-map-tier-5" = "crimson-temple-map-tier-5",
  "crimson-township-map-tier-5" = "crimson-township-map-tier-5",
  "dark-forest-map-tier-5" = "dark-forest-map-tier-5",
  "excavation-map-tier-5" = "excavation-map-tier-5",
  "moon-temple-map-tier-5" = "moon-temple-map-tier-5",
  "mud-geyser-map-tier-5" = "mud-geyser-map-tier-5",
  "shrine-map-tier-5" = "shrine-map-tier-5",
  "temple-map-tier-5" = "temple-map-tier-5",
  "thicket-map-tier-5" = "thicket-map-tier-5",
  "wharf-map-tier-5" = "wharf-map-tier-5",
}

/** All currencies belonging to the group `MapsTier6` (Maps (Tier 6)) */
export enum MapsTier6 {
  "arachnid-tomb-map-tier-6" = "arachnid-tomb-map-tier-6",
  "bone-crypt-map-tier-6" = "bone-crypt-map-tier-6",
  "caldera-map-tier-6" = "caldera-map-tier-6",
  "cells-map-tier-6" = "cells-map-tier-6",
  "defiled-cathedral-map-tier-6" = "defiled-cathedral-map-tier-6",
  "dry-sea-map-tier-6" = "dry-sea-map-tier-6",
  "factory-map-tier-6" = "factory-map-tier-6",
  "jungle-valley-map-tier-6" = "jungle-valley-map-tier-6",
  "lava-chamber-map-tier-6" = "lava-chamber-map-tier-6",
  "museum-map-tier-6" = "museum-map-tier-6",
  "overgrown-shrine-map-tier-6" = "overgrown-shrine-map-tier-6",
  "park-map-tier-6" = "park-map-tier-6",
  "plateau-map-tier-6" = "plateau-map-tier-6",
  "spider-forest-map-tier-6" = "spider-forest-map-tier-6",
  "waterways-map-tier-6" = "waterways-map-tier-6",
}

/** All currencies belonging to the group `MapsTier7` (Maps (Tier 7)) */
export enum MapsTier7 {
  "arachnid-nest-map-tier-7" = "arachnid-nest-map-tier-7",
  "atoll-map-tier-7" = "atoll-map-tier-7",
  "chateau-map-tier-7" = "chateau-map-tier-7",
  "colonnade-map-tier-7" = "colonnade-map-tier-7",
  "dungeon-map-tier-7" = "dungeon-map-tier-7",
  "fungal-hollow-map-tier-7" = "fungal-hollow-map-tier-7",
  "laboratory-map-tier-7" = "laboratory-map-tier-7",
  "lair-map-tier-7" = "lair-map-tier-7",
  "mausoleum-map-tier-7" = "mausoleum-map-tier-7",
  "necropolis-map-tier-7" = "necropolis-map-tier-7",
  "phantasmagoria-map-tier-7" = "phantasmagoria-map-tier-7",
  "primordial-pool-map-tier-7" = "primordial-pool-map-tier-7",
  "shore-map-tier-7" = "shore-map-tier-7",
  "summit-map-tier-7" = "summit-map-tier-7",
  "vaal-pyramid-map-tier-7" = "vaal-pyramid-map-tier-7",
}

/** All currencies belonging to the group `MapsTier8` (Maps (Tier 8)) */
export enum MapsTier8 {
  "acid-caverns-map-tier-8" = "acid-caverns-map-tier-8",
  "ancient-city-map-tier-8" = "ancient-city-map-tier-8",
  "barrows-map-tier-8" = "barrows-map-tier-8",
  "bog-map-tier-8" = "bog-map-tier-8",
  "canyon-map-tier-8" = "canyon-map-tier-8",
  "coral-ruins-map-tier-8" = "coral-ruins-map-tier-8",
  "crater-map-tier-8" = "crater-map-tier-8",
  "crimson-township-map-tier-8" = "crimson-township-map-tier-8",
  "frozen-cabins-map-tier-8" = "frozen-cabins-map-tier-8",
  "ghetto-map-tier-8" = "ghetto-map-tier-8",
  "maze-map-tier-8" = "maze-map-tier-8",
  "mud-geyser-map-tier-8" = "mud-geyser-map-tier-8",
  "overgrown-ruin-map-tier-8" = "overgrown-ruin-map-tier-8",
  "shrine-map-tier-8" = "shrine-map-tier-8",
  "strand-map-tier-8" = "strand-map-tier-8",
  "temple-map-tier-8" = "temple-map-tier-8",
  "terrace-map-tier-8" = "terrace-map-tier-8",
  "wasteland-map-tier-8" = "wasteland-map-tier-8",
  "wharf-map-tier-8" = "wharf-map-tier-8",
}

/** All currencies belonging to the group `MapsTier9` (Maps (Tier 9)) */
export enum MapsTier9 {
  "arachnid-tomb-map-tier-9" = "arachnid-tomb-map-tier-9",
  "bramble-valley-map-tier-9" = "bramble-valley-map-tier-9",
  "carcass-map-tier-9" = "carcass-map-tier-9",
  "colosseum-map-tier-9" = "colosseum-map-tier-9",
  "crimson-temple-map-tier-9" = "crimson-temple-map-tier-9",
  "dark-forest-map-tier-9" = "dark-forest-map-tier-9",
  "desert-map-tier-9" = "desert-map-tier-9",
  "dig-map-tier-9" = "dig-map-tier-9",
  "dry-sea-map-tier-9" = "dry-sea-map-tier-9",
  "excavation-map-tier-9" = "excavation-map-tier-9",
  "foundry-map-tier-9" = "foundry-map-tier-9",
  "jungle-valley-map-tier-9" = "jungle-valley-map-tier-9",
  "lava-chamber-map-tier-9" = "lava-chamber-map-tier-9",
  "moon-temple-map-tier-9" = "moon-temple-map-tier-9",
  "overgrown-shrine-map-tier-9" = "overgrown-shrine-map-tier-9",
  "pier-map-tier-9" = "pier-map-tier-9",
  "plateau-map-tier-9" = "plateau-map-tier-9",
  "residence-map-tier-9" = "residence-map-tier-9",
  "spider-forest-map-tier-9" = "spider-forest-map-tier-9",
  "thicket-map-tier-9" = "thicket-map-tier-9",
  "villa-map-tier-9" = "villa-map-tier-9",
}

/** All currencies belonging to the group `MapsTier10` (Maps (Tier 10)) */
export enum MapsTier10 {
  "arachnid-nest-map-tier-10" = "arachnid-nest-map-tier-10",
  "bone-crypt-map-tier-10" = "bone-crypt-map-tier-10",
  "caldera-map-tier-10" = "caldera-map-tier-10",
  "cells-map-tier-10" = "cells-map-tier-10",
  "cold-river-map-tier-10" = "cold-river-map-tier-10",
  "colonnade-map-tier-10" = "colonnade-map-tier-10",
  "defiled-cathedral-map-tier-10" = "defiled-cathedral-map-tier-10",
  "factory-map-tier-10" = "factory-map-tier-10",
  "fungal-hollow-map-tier-10" = "fungal-hollow-map-tier-10",
  "gardens-map-tier-10" = "gardens-map-tier-10",
  "lair-map-tier-10" = "lair-map-tier-10",
  "leyline-map-tier-10" = "leyline-map-tier-10",
  "mausoleum-map-tier-10" = "mausoleum-map-tier-10",
  "museum-map-tier-10" = "museum-map-tier-10",
  "necropolis-map-tier-10" = "necropolis-map-tier-10",
  "park-map-tier-10" = "park-map-tier-10",
  "racecourse-map-tier-10" = "racecourse-map-tier-10",
  "stagnation-map-tier-10" = "stagnation-map-tier-10",
  "summit-map-tier-10" = "summit-map-tier-10",
  "underground-river-map-tier-10" = "underground-river-map-tier-10",
  "waterways-map-tier-10" = "waterways-map-tier-10",
}

/** All currencies belonging to the group `MapsTier11` (Maps (Tier 11)) */
export enum MapsTier11 {
  "alleyways-map-tier-11" = "alleyways-map-tier-11",
  "ancient-city-map-tier-11" = "ancient-city-map-tier-11",
  "arena-map-tier-11" = "arena-map-tier-11",
  "atoll-map-tier-11" = "atoll-map-tier-11",
  "barrows-map-tier-11" = "barrows-map-tier-11",
  "belfry-map-tier-11" = "belfry-map-tier-11",
  "bog-map-tier-11" = "bog-map-tier-11",
  "canyon-map-tier-11" = "canyon-map-tier-11",
  "castle-ruins-map-tier-11" = "castle-ruins-map-tier-11",
  "chateau-map-tier-11" = "chateau-map-tier-11",
  "dungeon-map-tier-11" = "dungeon-map-tier-11",
  "ghetto-map-tier-11" = "ghetto-map-tier-11",
  "laboratory-map-tier-11" = "laboratory-map-tier-11",
  "maze-map-tier-11" = "maze-map-tier-11",
  "peninsula-map-tier-11" = "peninsula-map-tier-11",
  "phantasmagoria-map-tier-11" = "phantasmagoria-map-tier-11",
  "precinct-map-tier-11" = "precinct-map-tier-11",
  "primordial-pool-map-tier-11" = "primordial-pool-map-tier-11",
  "shore-map-tier-11" = "shore-map-tier-11",
  "vaal-pyramid-map-tier-11" = "vaal-pyramid-map-tier-11",
  "wasteland-map-tier-11" = "wasteland-map-tier-11",
}

/** All currencies belonging to the group `MapsTier12` (Maps (Tier 12)) */
export enum MapsTier12 {
  "acid-caverns-map-tier-12" = "acid-caverns-map-tier-12",
  "cemetery-map-tier-12" = "cemetery-map-tier-12",
  "coral-ruins-map-tier-12" = "coral-ruins-map-tier-12",
  "crater-map-tier-12" = "crater-map-tier-12",
  "crimson-township-map-tier-12" = "crimson-township-map-tier-12",
  "cursed-crypt-map-tier-12" = "cursed-crypt-map-tier-12",
  "desert-map-tier-12" = "desert-map-tier-12",
  "dig-map-tier-12" = "dig-map-tier-12",
  "foundry-map-tier-12" = "foundry-map-tier-12",
  "frozen-cabins-map-tier-12" = "frozen-cabins-map-tier-12",
  "marshes-map-tier-12" = "marshes-map-tier-12",
  "mud-geyser-map-tier-12" = "mud-geyser-map-tier-12",
  "overgrown-ruin-map-tier-12" = "overgrown-ruin-map-tier-12",
  "pier-map-tier-12" = "pier-map-tier-12",
  "port-map-tier-12" = "port-map-tier-12",
  "promenade-map-tier-12" = "promenade-map-tier-12",
  "residence-map-tier-12" = "residence-map-tier-12",
  "shrine-map-tier-12" = "shrine-map-tier-12",
  "silo-map-tier-12" = "silo-map-tier-12",
  "strand-map-tier-12" = "strand-map-tier-12",
  "temple-map-tier-12" = "temple-map-tier-12",
  "terrace-map-tier-12" = "terrace-map-tier-12",
  "villa-map-tier-12" = "villa-map-tier-12",
  "wharf-map-tier-12" = "wharf-map-tier-12",
}

/** All currencies belonging to the group `MapsTier13` (Maps (Tier 13)) */
export enum MapsTier13 {
  "arachnid-tomb-map-tier-13" = "arachnid-tomb-map-tier-13",
  "arsenal-map-tier-13" = "arsenal-map-tier-13",
  "bramble-valley-map-tier-13" = "bramble-valley-map-tier-13",
  "carcass-map-tier-13" = "carcass-map-tier-13",
  "cold-river-map-tier-13" = "cold-river-map-tier-13",
  "colosseum-map-tier-13" = "colosseum-map-tier-13",
  "crimson-temple-map-tier-13" = "crimson-temple-map-tier-13",
  "dark-forest-map-tier-13" = "dark-forest-map-tier-13",
  "dry-sea-map-tier-13" = "dry-sea-map-tier-13",
  "excavation-map-tier-13" = "excavation-map-tier-13",
  "gardens-map-tier-13" = "gardens-map-tier-13",
  "jungle-valley-map-tier-13" = "jungle-valley-map-tier-13",
  "lava-chamber-map-tier-13" = "lava-chamber-map-tier-13",
  "lava-lake-map-tier-13" = "lava-lake-map-tier-13",
  "leyline-map-tier-13" = "leyline-map-tier-13",
  "moon-temple-map-tier-13" = "moon-temple-map-tier-13",
  "orchard-map-tier-13" = "orchard-map-tier-13",
  "overgrown-shrine-map-tier-13" = "overgrown-shrine-map-tier-13",
  "pen-map-tier-13" = "pen-map-tier-13",
  "plateau-map-tier-13" = "plateau-map-tier-13",
  "racecourse-map-tier-13" = "racecourse-map-tier-13",
  "spider-forest-map-tier-13" = "spider-forest-map-tier-13",
  "stagnation-map-tier-13" = "stagnation-map-tier-13",
  "sulphur-vents-map-tier-13" = "sulphur-vents-map-tier-13",
  "thicket-map-tier-13" = "thicket-map-tier-13",
  "underground-river-map-tier-13" = "underground-river-map-tier-13",
}

/** All currencies belonging to the group `MapsTier14` (Maps (Tier 14)) */
export enum MapsTier14 {
  "alleyways-map-tier-14" = "alleyways-map-tier-14",
  "arachnid-nest-map-tier-14" = "arachnid-nest-map-tier-14",
  "arena-map-tier-14" = "arena-map-tier-14",
  "armoury-map-tier-14" = "armoury-map-tier-14",
  "ashen-wood-map-tier-14" = "ashen-wood-map-tier-14",
  "belfry-map-tier-14" = "belfry-map-tier-14",
  "bone-crypt-map-tier-14" = "bone-crypt-map-tier-14",
  "caldera-map-tier-14" = "caldera-map-tier-14",
  "castle-ruins-map-tier-14" = "castle-ruins-map-tier-14",
  "cells-map-tier-14" = "cells-map-tier-14",
  "colonnade-map-tier-14" = "colonnade-map-tier-14",
  "defiled-cathedral-map-tier-14" = "defiled-cathedral-map-tier-14",
  "factory-map-tier-14" = "factory-map-tier-14",
  "fungal-hollow-map-tier-14" = "fungal-hollow-map-tier-14",
  "lair-map-tier-14" = "lair-map-tier-14",
  "mausoleum-map-tier-14" = "mausoleum-map-tier-14",
  "mesa-map-tier-14" = "mesa-map-tier-14",
  "museum-map-tier-14" = "museum-map-tier-14",
  "necropolis-map-tier-14" = "necropolis-map-tier-14",
  "park-map-tier-14" = "park-map-tier-14",
  "peninsula-map-tier-14" = "peninsula-map-tier-14",
  "plaza-map-tier-14" = "plaza-map-tier-14",
  "precinct-map-tier-14" = "precinct-map-tier-14",
  "summit-map-tier-14" = "summit-map-tier-14",
  "underground-sea-map-tier-14" = "underground-sea-map-tier-14",
  "waterways-map-tier-14" = "waterways-map-tier-14",
}

/** All currencies belonging to the group `MapsTier15` (Maps (Tier 15)) */
export enum MapsTier15 {
  "ancient-city-map-tier-15" = "ancient-city-map-tier-15",
  "arcade-map-tier-15" = "arcade-map-tier-15",
  "atoll-map-tier-15" = "atoll-map-tier-15",
  "barrows-map-tier-15" = "barrows-map-tier-15",
  "bog-map-tier-15" = "bog-map-tier-15",
  "canyon-map-tier-15" = "canyon-map-tier-15",
  "cemetery-map-tier-15" = "cemetery-map-tier-15",
  "chateau-map-tier-15" = "chateau-map-tier-15",
  "cursed-crypt-map-tier-15" = "cursed-crypt-map-tier-15",
  "dunes-map-tier-15" = "dunes-map-tier-15",
  "dungeon-map-tier-15" = "dungeon-map-tier-15",
  "forking-river-map-tier-15" = "forking-river-map-tier-15",
  "ghetto-map-tier-15" = "ghetto-map-tier-15",
  "grotto-map-tier-15" = "grotto-map-tier-15",
  "laboratory-map-tier-15" = "laboratory-map-tier-15",
  "marshes-map-tier-15" = "marshes-map-tier-15",
  "maze-map-tier-15" = "maze-map-tier-15",
  "phantasmagoria-map-tier-15" = "phantasmagoria-map-tier-15",
  "port-map-tier-15" = "port-map-tier-15",
  "primordial-pool-map-tier-15" = "primordial-pool-map-tier-15",
  "promenade-map-tier-15" = "promenade-map-tier-15",
  "shore-map-tier-15" = "shore-map-tier-15",
  "silo-map-tier-15" = "silo-map-tier-15",
  "vaal-pyramid-map-tier-15" = "vaal-pyramid-map-tier-15",
  "vault-map-tier-15" = "vault-map-tier-15",
  "wasteland-map-tier-15" = "wasteland-map-tier-15",
}

/** All currencies belonging to the group `MapsTier16` (Maps (Tier 16)) */
export enum MapsTier16 {
  "acid-caverns-map-tier-16" = "acid-caverns-map-tier-16",
  "alleyways-map-tier-16" = "alleyways-map-tier-16",
  "ancient-city-map-tier-16" = "ancient-city-map-tier-16",
  "arachnid-nest-map-tier-16" = "arachnid-nest-map-tier-16",
  "arachnid-tomb-map-tier-16" = "arachnid-tomb-map-tier-16",
  "arcade-map-tier-16" = "arcade-map-tier-16",
  "arena-map-tier-16" = "arena-map-tier-16",
  "arid-lake-map-tier-16" = "arid-lake-map-tier-16",
  "armoury-map-tier-16" = "armoury-map-tier-16",
  "arsenal-map-tier-16" = "arsenal-map-tier-16",
  "ashen-wood-map-tier-16" = "ashen-wood-map-tier-16",
  "atoll-map-tier-16" = "atoll-map-tier-16",
  "barrows-map-tier-16" = "barrows-map-tier-16",
  "belfry-map-tier-16" = "belfry-map-tier-16",
  "bog-map-tier-16" = "bog-map-tier-16",
  "bone-crypt-map-tier-16" = "bone-crypt-map-tier-16",
  "bramble-valley-map-tier-16" = "bramble-valley-map-tier-16",
  "caldera-map-tier-16" = "caldera-map-tier-16",
  "canyon-map-tier-16" = "canyon-map-tier-16",
  "carcass-map-tier-16" = "carcass-map-tier-16",
  "castle-ruins-map-tier-16" = "castle-ruins-map-tier-16",
  "cells-map-tier-16" = "cells-map-tier-16",
  "cemetery-map-tier-16" = "cemetery-map-tier-16",
  "chateau-map-tier-16" = "chateau-map-tier-16",
  "cold-river-map-tier-16" = "cold-river-map-tier-16",
  "colonnade-map-tier-16" = "colonnade-map-tier-16",
  "colosseum-map-tier-16" = "colosseum-map-tier-16",
  "coral-ruins-map-tier-16" = "coral-ruins-map-tier-16",
  "crater-map-tier-16" = "crater-map-tier-16",
  "crimson-temple-map-tier-16" = "crimson-temple-map-tier-16",
  "crimson-township-map-tier-16" = "crimson-township-map-tier-16",
  "cursed-crypt-map-tier-16" = "cursed-crypt-map-tier-16",
  "dark-forest-map-tier-16" = "dark-forest-map-tier-16",
  "defiled-cathedral-map-tier-16" = "defiled-cathedral-map-tier-16",
  "desert-map-tier-16" = "desert-map-tier-16",
  "dig-map-tier-16" = "dig-map-tier-16",
  "dry-sea-map-tier-16" = "dry-sea-map-tier-16",
  "dunes-map-tier-16" = "dunes-map-tier-16",
  "dungeon-map-tier-16" = "dungeon-map-tier-16",
  "excavation-map-tier-16" = "excavation-map-tier-16",
  "factory-map-tier-16" = "factory-map-tier-16",
  "forge-of-the-phoenix-map" = "forge-of-the-phoenix-map",
  "forge-of-the-phoenix-map-tier-16" = "forge-of-the-phoenix-map-tier-16",
  "forking-river-map-tier-16" = "forking-river-map-tier-16",
  "foundry-map-tier-16" = "foundry-map-tier-16",
  "frozen-cabins-map-tier-16" = "frozen-cabins-map-tier-16",
  "fungal-hollow-map-tier-16" = "fungal-hollow-map-tier-16",
  "gardens-map-tier-16" = "gardens-map-tier-16",
  "ghetto-map-tier-16" = "ghetto-map-tier-16",
  "grave-trough-map-tier-16" = "grave-trough-map-tier-16",
  "grotto-map-tier-16" = "grotto-map-tier-16",
  "jungle-valley-map-tier-16" = "jungle-valley-map-tier-16",
  "laboratory-map-tier-16" = "laboratory-map-tier-16",
  "lair-map-tier-16" = "lair-map-tier-16",
  "lair-of-the-hydra-map" = "lair-of-the-hydra-map",
  "lair-of-the-hydra-map-tier-16" = "lair-of-the-hydra-map-tier-16",
  "lava-chamber-map-tier-16" = "lava-chamber-map-tier-16",
  "lava-lake-map-tier-16" = "lava-lake-map-tier-16",
  "leyline-map-tier-16" = "leyline-map-tier-16",
  "marshes-map-tier-16" = "marshes-map-tier-16",
  "mausoleum-map-tier-16" = "mausoleum-map-tier-16",
  "maze-map-tier-16" = "maze-map-tier-16",
  "maze-of-the-minotaur-map" = "maze-of-the-minotaur-map",
  "maze-of-the-minotaur-map-tier-16" = "maze-of-the-minotaur-map-tier-16",
  "mesa-map-tier-16" = "mesa-map-tier-16",
  "moon-temple-map-tier-16" = "moon-temple-map-tier-16",
  "mud-geyser-map-tier-16" = "mud-geyser-map-tier-16",
  "museum-map-tier-16" = "museum-map-tier-16",
  "necropolis-map-tier-16" = "necropolis-map-tier-16",
  "orchard-map-tier-16" = "orchard-map-tier-16",
  "overgrown-ruin-map-tier-16" = "overgrown-ruin-map-tier-16",
  "overgrown-shrine-map-tier-16" = "overgrown-shrine-map-tier-16",
  "park-map-tier-16" = "park-map-tier-16",
  "pen-map-tier-16" = "pen-map-tier-16",
  "peninsula-map-tier-16" = "peninsula-map-tier-16",
  "phantasmagoria-map-tier-16" = "phantasmagoria-map-tier-16",
  "pier-map-tier-16" = "pier-map-tier-16",
  "pit-of-the-chimera-map" = "pit-of-the-chimera-map",
  "pit-of-the-chimera-map-tier-16" = "pit-of-the-chimera-map-tier-16",
  "plateau-map-tier-16" = "plateau-map-tier-16",
  "plaza-map-tier-16" = "plaza-map-tier-16",
  "port-map-tier-16" = "port-map-tier-16",
  "precinct-map-tier-16" = "precinct-map-tier-16",
  "primordial-pool-map-tier-16" = "primordial-pool-map-tier-16",
  "promenade-map-tier-16" = "promenade-map-tier-16",
  "racecourse-map-tier-16" = "racecourse-map-tier-16",
  "ramparts-map-tier-16" = "ramparts-map-tier-16",
  "residence-map-tier-16" = "residence-map-tier-16",
  "shore-map-tier-16" = "shore-map-tier-16",
  "shrine-map-tier-16" = "shrine-map-tier-16",
  "silo-map-tier-16" = "silo-map-tier-16",
  "spider-forest-map-tier-16" = "spider-forest-map-tier-16",
  "stagnation-map-tier-16" = "stagnation-map-tier-16",
  "strand-map-tier-16" = "strand-map-tier-16",
  "sulphur-vents-map-tier-16" = "sulphur-vents-map-tier-16",
  "summit-map-tier-16" = "summit-map-tier-16",
  "temple-map-tier-16" = "temple-map-tier-16",
  "terrace-map-tier-16" = "terrace-map-tier-16",
  "thicket-map-tier-16" = "thicket-map-tier-16",
  "underground-river-map-tier-16" = "underground-river-map-tier-16",
  "underground-sea-map-tier-16" = "underground-sea-map-tier-16",
  "vaal-pyramid-map-tier-16" = "vaal-pyramid-map-tier-16",
  "vaal-temple-map-tier-16" = "vaal-temple-map-tier-16",
  "vault-map-tier-16" = "vault-map-tier-16",
  "villa-map-tier-16" = "villa-map-tier-16",
  "waste-pool-map-tier-16" = "waste-pool-map-tier-16",
  "wasteland-map-tier-16" = "wasteland-map-tier-16",
  "waterways-map-tier-16" = "waterways-map-tier-16",
  "wharf-map-tier-16" = "wharf-map-tier-16",
}

/** All currencies belonging to the group `MapsBlighted` (Maps (Blighted)) */
export enum MapsBlighted {
  "blighted-acid-caverns-map" = "blighted-acid-caverns-map",
  "blighted-alleyways-map" = "blighted-alleyways-map",
  "blighted-ancient-city-map" = "blighted-ancient-city-map",
  "blighted-arachnid-nest-map" = "blighted-arachnid-nest-map",
  "blighted-arcade-map" = "blighted-arcade-map",
  "blighted-arid-lake-map" = "blighted-arid-lake-map",
  "blighted-armoury-map" = "blighted-armoury-map",
  "blighted-arsenal-map" = "blighted-arsenal-map",
  "blighted-ashen-wood-map" = "blighted-ashen-wood-map",
  "blighted-atoll-map" = "blighted-atoll-map",
  "blighted-barrows-map" = "blighted-barrows-map",
  "blighted-belfry-map" = "blighted-belfry-map",
  "blighted-bog-map" = "blighted-bog-map",
  "blighted-bone-crypt-map" = "blighted-bone-crypt-map",
  "blighted-bramble-valley-map" = "blighted-bramble-valley-map",
  "blighted-caldera-map" = "blighted-caldera-map",
  "blighted-canyon-map" = "blighted-canyon-map",
  "blighted-castle-ruins-map" = "blighted-castle-ruins-map",
  "blighted-cells-map" = "blighted-cells-map",
  "blighted-cemetery-map" = "blighted-cemetery-map",
  "blighted-chateau-map" = "blighted-chateau-map",
  "blighted-cold-river-map" = "blighted-cold-river-map",
  "blighted-colonnade-map" = "blighted-colonnade-map",
  "blighted-coral-ruins-map" = "blighted-coral-ruins-map",
  "blighted-crimson-temple-map" = "blighted-crimson-temple-map",
  "blighted-crimson-township-map" = "blighted-crimson-township-map",
  "blighted-cursed-crypt-map" = "blighted-cursed-crypt-map",
  "blighted-dark-forest-map" = "blighted-dark-forest-map",
  "blighted-defiled-cathedral-map" = "blighted-defiled-cathedral-map",
  "blighted-desert-map" = "blighted-desert-map",
  "blighted-dig-map" = "blighted-dig-map",
  "blighted-dry-sea-map" = "blighted-dry-sea-map",
  "blighted-dunes-map" = "blighted-dunes-map",
  "blighted-dungeon-map" = "blighted-dungeon-map",
  "blighted-forking-river-map" = "blighted-forking-river-map",
  "blighted-foundry-map" = "blighted-foundry-map",
  "blighted-gardens-map" = "blighted-gardens-map",
  "blighted-ghetto-map" = "blighted-ghetto-map",
  "blighted-grave-trough-map" = "blighted-grave-trough-map",
  "blighted-jungle-valley-map" = "blighted-jungle-valley-map",
  "blighted-laboratory-map" = "blighted-laboratory-map",
  "blighted-lair-map" = "blighted-lair-map",
  "blighted-lava-chamber-map" = "blighted-lava-chamber-map",
  "blighted-lava-lake-map" = "blighted-lava-lake-map",
  "blighted-leyline-map" = "blighted-leyline-map",
  "blighted-marshes-map" = "blighted-marshes-map",
  "blighted-mausoleum-map" = "blighted-mausoleum-map",
  "blighted-mesa-map" = "blighted-mesa-map",
  "blighted-moon-temple-map" = "blighted-moon-temple-map",
  "blighted-mud-geyser-map" = "blighted-mud-geyser-map",
  "blighted-museum-map" = "blighted-museum-map",
  "blighted-necropolis-map" = "blighted-necropolis-map",
  "blighted-orchard-map" = "blighted-orchard-map",
  "blighted-overgrown-shrine-map" = "blighted-overgrown-shrine-map",
  "blighted-park-map" = "blighted-park-map",
  "blighted-pen-map" = "blighted-pen-map",
  "blighted-peninsula-map" = "blighted-peninsula-map",
  "blighted-plateau-map" = "blighted-plateau-map",
  "blighted-plaza-map" = "blighted-plaza-map",
  "blighted-port-map" = "blighted-port-map",
  "blighted-precinct-map" = "blighted-precinct-map",
  "blighted-primordial-pool-map" = "blighted-primordial-pool-map",
  "blighted-promenade-map" = "blighted-promenade-map",
  "blighted-racecourse-map" = "blighted-racecourse-map",
  "blighted-ramparts-map" = "blighted-ramparts-map",
  "blighted-shore-map" = "blighted-shore-map",
  "blighted-shrine-map" = "blighted-shrine-map",
  "blighted-silo-map" = "blighted-silo-map",
  "blighted-spider-forest-map" = "blighted-spider-forest-map",
  "blighted-stagnation-map" = "blighted-stagnation-map",
  "blighted-strand-map" = "blighted-strand-map",
  "blighted-sulphur-vents-map" = "blighted-sulphur-vents-map",
  "blighted-summit-map" = "blighted-summit-map",
  "blighted-temple-map" = "blighted-temple-map",
  "blighted-thicket-map" = "blighted-thicket-map",
  "blighted-underground-river-map" = "blighted-underground-river-map",
  "blighted-underground-sea-map" = "blighted-underground-sea-map",
  "blighted-vault-map" = "blighted-vault-map",
  "blighted-villa-map" = "blighted-villa-map",
  "blighted-waste-pool-map" = "blighted-waste-pool-map",
  "blighted-wasteland-map" = "blighted-wasteland-map",
  "blighted-wharf-map" = "blighted-wharf-map",
}

/** All currencies belonging to the group `MapsUberBlighted` (Maps (Blight-ravaged)) */
export enum MapsUberBlighted {
  "blight-ravaged-arcade-map" = "blight-ravaged-arcade-map",
  "blight-ravaged-arid-lake-map" = "blight-ravaged-arid-lake-map",
  "blight-ravaged-armoury-map" = "blight-ravaged-armoury-map",
  "blight-ravaged-ashen-wood-map" = "blight-ravaged-ashen-wood-map",
  "blight-ravaged-dunes-map" = "blight-ravaged-dunes-map",
  "blight-ravaged-forking-river-map" = "blight-ravaged-forking-river-map",
  "blight-ravaged-grave-trough-map" = "blight-ravaged-grave-trough-map",
  "blight-ravaged-mesa-map" = "blight-ravaged-mesa-map",
  "blight-ravaged-plaza-map" = "blight-ravaged-plaza-map",
  "blight-ravaged-ramparts-map" = "blight-ravaged-ramparts-map",
  "blight-ravaged-underground-sea-map" = "blight-ravaged-underground-sea-map",
  "blight-ravaged-vault-map" = "blight-ravaged-vault-map",
  "blight-ravaged-waste-pool-map" = "blight-ravaged-waste-pool-map",
}

/** All currencies belonging to the group `MapsUnique` (Maps (Unique)) */
export enum MapsUnique {
  "actons-nightmare-tier-6" = "actons-nightmare-tier-6",
  "actons-nightmare-tier-9" = "actons-nightmare-tier-9",
  "actons-nightmare-tier-13" = "actons-nightmare-tier-13",
  "actons-nightmare-tier-16" = "actons-nightmare-tier-16",
  "altered-distant-memory-tier-10" = "altered-distant-memory-tier-10",
  "augmented-distant-memory-tier-10" = "augmented-distant-memory-tier-10",
  "caer-blaidd-tier-10" = "caer-blaidd-tier-10",
  "caer-blaidd-tier-13" = "caer-blaidd-tier-13",
  "caer-blaidd-tier-16" = "caer-blaidd-tier-16",
  "cortex-tier-10" = "cortex-tier-10",
  "death-and-taxes-tier-7" = "death-and-taxes-tier-7",
  "death-and-taxes-tier-10" = "death-and-taxes-tier-10",
  "death-and-taxes-tier-14" = "death-and-taxes-tier-14",
  "death-and-taxes-tier-16" = "death-and-taxes-tier-16",
  "doryanis-machinarium-tier-8" = "doryanis-machinarium-tier-8",
  "doryanis-machinarium-tier-11" = "doryanis-machinarium-tier-11",
  "doryanis-machinarium-tier-15" = "doryanis-machinarium-tier-15",
  "doryanis-machinarium-tier-16" = "doryanis-machinarium-tier-16",
  "hall-of-grandmasters-tier-12" = "hall-of-grandmasters-tier-12",
  "hall-of-grandmasters-tier-15" = "hall-of-grandmasters-tier-15",
  "hall-of-grandmasters-tier-16" = "hall-of-grandmasters-tier-16",
  "hallowed-ground-tier-12" = "hallowed-ground-tier-12",
  "hallowed-ground-tier-15" = "hallowed-ground-tier-15",
  "hallowed-ground-tier-16" = "hallowed-ground-tier-16",
  "infused-beachhead-tier-16" = "infused-beachhead-tier-16",
  "maelstrom-of-chaos-tier-4" = "maelstrom-of-chaos-tier-4",
  "maelstrom-of-chaos-tier-7" = "maelstrom-of-chaos-tier-7",
  "maelstrom-of-chaos-tier-11" = "maelstrom-of-chaos-tier-11",
  "maelstrom-of-chaos-tier-15" = "maelstrom-of-chaos-tier-15",
  "maelstrom-of-chaos-tier-16" = "maelstrom-of-chaos-tier-16",
  "mao-kun-tier-4" = "mao-kun-tier-4",
  "mao-kun-tier-7" = "mao-kun-tier-7",
  "mao-kun-tier-11" = "mao-kun-tier-11",
  "mao-kun-tier-15" = "mao-kun-tier-15",
  "mao-kun-tier-16" = "mao-kun-tier-16",
  "obas-cursed-trove-tier-14" = "obas-cursed-trove-tier-14",
  "obas-cursed-trove-tier-16" = "obas-cursed-trove-tier-16",
  "olmecs-sanctum-tier-3" = "olmecs-sanctum-tier-3",
  "olmecs-sanctum-tier-6" = "olmecs-sanctum-tier-6",
  "olmecs-sanctum-tier-10" = "olmecs-sanctum-tier-10",
  "olmecs-sanctum-tier-14" = "olmecs-sanctum-tier-14",
  "olmecs-sanctum-tier-16" = "olmecs-sanctum-tier-16",
  "pillars-of-arun-tier-15" = "pillars-of-arun-tier-15",
  "pillars-of-arun-tier-16" = "pillars-of-arun-tier-16",
  "poorjoys-asylum-tier-5" = "poorjoys-asylum-tier-5",
  "poorjoys-asylum-tier-8" = "poorjoys-asylum-tier-8",
  "poorjoys-asylum-tier-12" = "poorjoys-asylum-tier-12",
  "poorjoys-asylum-tier-16" = "poorjoys-asylum-tier-16",
  "replica-cortex-tier-10" = "replica-cortex-tier-10",
  "replica-pillars-of-arun-tier-15" = "replica-pillars-of-arun-tier-15",
  "replica-pillars-of-arun-tier-16" = "replica-pillars-of-arun-tier-16",
  "replica-poorjoys-asylum-tier-5" = "replica-poorjoys-asylum-tier-5",
  "replica-poorjoys-asylum-tier-8" = "replica-poorjoys-asylum-tier-8",
  "replica-poorjoys-asylum-tier-12" = "replica-poorjoys-asylum-tier-12",
  "replica-poorjoys-asylum-tier-16" = "replica-poorjoys-asylum-tier-16",
  "rewritten-distant-memory-tier-10" = "rewritten-distant-memory-tier-10",
  "the-beachhead-tier-5" = "the-beachhead-tier-5",
  "the-beachhead-tier-10" = "the-beachhead-tier-10",
  "the-beachhead-tier-15" = "the-beachhead-tier-15",
  "the-cowards-trial-tier-15" = "the-cowards-trial-tier-15",
  "the-cowards-trial-tier-16" = "the-cowards-trial-tier-16",
  "the-putrid-cloister-tier-3" = "the-putrid-cloister-tier-3",
  "the-putrid-cloister-tier-6" = "the-putrid-cloister-tier-6",
  "the-putrid-cloister-tier-10" = "the-putrid-cloister-tier-10",
  "the-putrid-cloister-tier-14" = "the-putrid-cloister-tier-14",
  "the-putrid-cloister-tier-16" = "the-putrid-cloister-tier-16",
  "the-tower-of-ordeals" = "the-tower-of-ordeals",
  "the-twilight-temple-tier-2" = "the-twilight-temple-tier-2",
  "the-twilight-temple-tier-5" = "the-twilight-temple-tier-5",
  "the-twilight-temple-tier-9" = "the-twilight-temple-tier-9",
  "the-twilight-temple-tier-13" = "the-twilight-temple-tier-13",
  "the-twilight-temple-tier-16" = "the-twilight-temple-tier-16",
  "the-vinktar-square-tier-7" = "the-vinktar-square-tier-7",
  "the-vinktar-square-tier-10" = "the-vinktar-square-tier-10",
  "the-vinktar-square-tier-14" = "the-vinktar-square-tier-14",
  "the-vinktar-square-tier-16" = "the-vinktar-square-tier-16",
  "twisted-distant-memory-tier-10" = "twisted-distant-memory-tier-10",
  "vaults-of-atziri-tier-4" = "vaults-of-atziri-tier-4",
  "vaults-of-atziri-tier-7" = "vaults-of-atziri-tier-7",
  "vaults-of-atziri-tier-11" = "vaults-of-atziri-tier-11",
  "vaults-of-atziri-tier-15" = "vaults-of-atziri-tier-15",
  "vaults-of-atziri-tier-16" = "vaults-of-atziri-tier-16",
  "whakawairua-tuahu-tier-1" = "whakawairua-tuahu-tier-1",
  "whakawairua-tuahu-tier-4" = "whakawairua-tuahu-tier-4",
  "whakawairua-tuahu-tier-8" = "whakawairua-tuahu-tier-8",
  "whakawairua-tuahu-tier-12" = "whakawairua-tuahu-tier-12",
  "whakawairua-tuahu-tier-16" = "whakawairua-tuahu-tier-16",
}

/** All currencies belonging to the group `Misc` (Misc) */
export enum Misc {}

/** All possible currency IDs as defined by the PoE Trade API */
export type TradeCurrencyId =
  | Currency
  | ExoticCurrency
  | Splinters
  | Fragments
  | MemoryLine
  | ScoutingReport
  | Expedition
  | DeliriumOrbs
  | Catalysts
  | Oils
  | Incubators
  | Scarabs
  | DelveResonators
  | DelveFossils
  | Essences
  | Cards
  | MapsTier1
  | MapsTier2
  | MapsTier3
  | MapsTier4
  | MapsTier5
  | MapsTier6
  | MapsTier7
  | MapsTier8
  | MapsTier9
  | MapsTier10
  | MapsTier11
  | MapsTier12
  | MapsTier13
  | MapsTier14
  | MapsTier15
  | MapsTier16
  | MapsBlighted
  | MapsUberBlighted
  | MapsUnique
  | Misc;
