/**
 * The currency groups as defined by the PoE Trade API.
 * Every currency item belongs to one group.
 */
export enum TradeCurrencyGroup {
  Currency = "Currency",
  ExoticCurrency = "ExoticCurrency",
  Splinters = "Splinters",
  Fragments = "Fragments",
  MemoryLine = "MemoryLine",
  ScoutingReport = "ScoutingReport",
  Expedition = "Expedition",
  DeliriumOrbs = "DeliriumOrbs",
  Catalysts = "Catalysts",
  Oils = "Oils",
  Incubators = "Incubators",
  Scarabs = "Scarabs",
  DelveResonators = "DelveResonators",
  DelveFossils = "DelveFossils",
  Essences = "Essences",
  Cards = "Cards",
  MapsTier1 = "MapsTier1",
  MapsTier2 = "MapsTier2",
  MapsTier3 = "MapsTier3",
  MapsTier4 = "MapsTier4",
  MapsTier5 = "MapsTier5",
  MapsTier6 = "MapsTier6",
  MapsTier7 = "MapsTier7",
  MapsTier8 = "MapsTier8",
  MapsTier9 = "MapsTier9",
  MapsTier10 = "MapsTier10",
  MapsTier11 = "MapsTier11",
  MapsTier12 = "MapsTier12",
  MapsTier13 = "MapsTier13",
  MapsTier14 = "MapsTier14",
  MapsTier15 = "MapsTier15",
  MapsTier16 = "MapsTier16",
  MapsBlighted = "MapsBlighted",
  MapsUberBlighted = "MapsUberBlighted",
  MapsUnique = "MapsUnique",
  Misc = "Misc",
}
